/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMA_H_RPCGEN
#define _SOMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct valores {
	float valor1;
	float valor2;
};
typedef struct valores valores;

#define Soma 200
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define ADICAO 1
extern  float * adicao_100(valores *, CLIENT *);
extern  float * adicao_100_svc(valores *, struct svc_req *);
extern int soma_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADICAO 1
extern  float * adicao_100();
extern  float * adicao_100_svc();
extern int soma_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_valores (XDR *, valores*);

#else /* K&R C */
extern bool_t xdr_valores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMA_H_RPCGEN */
