/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "soma.h"

bool_t
xdr_valores (XDR *xdrs, valores *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->valor1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor2))
		 return FALSE;
	return TRUE;
}
